### ISSUE TITLE
Pulp dependency incorrect

### ISSUE THREAD

**Issue by stumitchell** [leliel12/scikit-criteria#12]
please note
https://github.com/coin-or/pulp/issues/286

You should probably
1. update your pulp dependency to pulp not pulp-py3
2. not use the pulp.solvers api
3. do a new release to pypi

**Comment by leliel12** [comment]
checked... tall this is my proyect for my summer (I am in the south)

**Comment by leliel12** [comment]
Hi guys thanks to @dand-oss the version 0.2.11 works again with the new pulp version.

Please upgrade with `pip install -U pulp scikit-criteria` (the `-U` is important) 

I currently working on scikit-criteria 0.5, with an entire redesign to make more easy create multiple experiments (more like scikit-learn pipelines) please subscribe to the scikit-criteria mailing list) https://groups.google.com/forum/#!forum/scikit-criteria
