### ISSUE TITLE
website down?

### ISSUE THREAD

**Issue by JedStephens** [leliel12/scikit-criteria#14]
When navigating to: http://scikit-criteria.org/ the page cannot be loaded. Is this expected? Can we get a version going even if it the a zip of the public folder in uploaded to this repo.

**Comment by leliel12** [comment]
Thanks for the issue, i just reconfigured the domain. In the meantime https://scikit-criteria.readthedocs.io << this URL always run. I just started to redesign entirely scikit criteria

**Comment by leliel12** [comment]
fixed

**Comment by JedStephens** [comment]
Appreciated!
