### ISSUE TITLE
What is `b`?

### ISSUE THREAD

**Issue by elcolie** [leliel12/scikit-criteria#16]
[SIMUS](https://scikit-criteria.readthedocs.io/en/latest/tutorial/simus.html)

At first it is one column call `Right side value`
![image](https://user-images.githubusercontent.com/18206728/129501532-8480a96f-7442-46a8-8559-566955990b4e.png)

Later on it is `b` and then you put it in `b` argument
![image](https://user-images.githubusercontent.com/18206728/129501542-a9c0fccc-613e-44fd-9747-59e185182de0.png)

**Questions**
1. What is `Right side value`?
2. What is `b`?
3. Can set `b` equal to list of `None`?

**Comment by leliel12** [comment]
The right side vector. You need to check the original simus paper.

Github issues are not for q&a please join the mailing list

https://groups.google.com/g/scikit-criteria

**Comment by leliel12** [comment]
I just check and I found the original paper is in Spanish :Argentina: 

Ok, send you an email.  Please join the mailing list.
