### ISSUE TITLE
PulpSolverError

### ISSUE THREAD

**Issue by elcolie** [leliel12/scikit-criteria#17]
I am following the SIMUS solvers and three of them are unavailable
`git+https://github.com/leliel12/scikit-criteria.git@1ca7667e08e79d551f8241278c939f604800d81b`

```
dm = SIMUS(solver='glpk')
PulpSolverError: PuLP: cannot execute glpsol


dm = SIMUS(solver='gurobi')
PulpSolverError: GUROBI: Not Available


dm = SIMUS(solver='cplex')
PulpSolverError: PuLP: cannot execute cplex
```

**Comment by leliel12** [comment]
You need to install it separatelly. PuLP only cames with a default solver.

Please check the PuLP documentation
https://coin-or.github.io/pulp/
