### ISSUE TITLE
Did not understand documentation

### ISSUE THREAD

**Issue by LordXyTh** [leliel12/scikit-criteria#7]
On the [Conceptual Overview](https://scikit-criteria.readthedocs.io/en/latest/tutorial/quickstart.html#Conceptual-Overview) page, the following like was confusing:

> The criteria vector must be a 1D array-like whit the same number of elements than columns has the alternative mattrix (mtx) where every component represent the optimal sense of every criteria.

Can you please re-explain?

**Comment by leliel12** [comment]
For example the next preference matrix:

|    | c0  | c1  | c2  |
|----|-----|-----|-----|
|    | _min_ | _max_ | _max_ |
| **a0** | 1   | 2   | 2   |
| **a1** | 4   | 5   | 6   |

You has 2 alternatives in the rows (**a1** and **a0***), and 3 criteria (**c1**, **c2**, **c0**) in the columns. The number of optimal sens are the number of criteria (3). In scikit criteria this can be expresed as follows


```ipython
ipython
import Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from skcriteria import Data

In [2]: mtx = [
   ...:     [1, 2, 3],
   ...:     [4, 5, 6]]
   ...:     

In [3]: criteria = [min, max, max]

In [4]: data = Data(mtx=mtx, criteria=criteria)

In [5]: data
Out[5]: 
 ALT./CRIT.    C0 (min)    C1 (max)    C2 (max)
------------  ----------  ----------  ----------
     A0           1           2           3
     A1           4           5           6
```

My native tongue is not english if you want to contribute to the documentation is always wanted.

**Comment by leliel12** [comment]
this is a question not an issue
